name: "Dispatch"
description: "This action triggers the E2E tests on the defined environment"

inputs:
  environment:
    description: "The environment to run the E2E tests for"
    required: true
  opToken:
    description: "1Password token used to retrieve the required secrets"
    required: true

runs:
  using: "composite"
  steps:
    - name: Load secrets
      id: load-secrets
      uses: 1password/load-secrets-action@v2.0.0
      with:
        export-env: false
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.opToken }}
        GH_APP_QA: op://apikeys_production/gh-app-qa/credential

    - name: Trigger E2E tests
      shell: bash
      run: |
        event_type="app_e2e_tests_dispatched"
        token="${{ steps.load-secrets.outputs.GH_APP_QA }}"
        environment="${{ inputs.environment }}"

        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $token" \
          -d '{"event_type": "'"$event_type"'", "client_payload": {"environment": "'"$environment"'"}}' \
          https://api.github.com/repos/aragon/app-qa/dispatches
