import { testWithSynpress } from "@synthetixio/synpress";
import { metaMaskFixtures } from "@synthetixio/synpress/playwright";
import basicSetup from "../basic.setup";

const test = testWithSynpress(metaMaskFixtures(basicSetup));

const { expect } = test;

test("Admin Plugin - Create DAO", async ({ page, metamask }) => {
  await page.getByRole("button", { name: "Connect" }).click();
  await page.waitForTimeout(3000);
  await page.getByRole("button", { name: "Connect" }).click();
  await page
    .locator("wui-text")
    .filter({ hasText: "MetaMask" })
    .locator("slot")
    .click();
  await metamask.connectToDapp();
  await metamask.approveSwitchNetwork();
  await page.waitForTimeout(3000);
  await metamask.switchNetwork("Sepolia", true);
  await page.getByRole("button", { name: "DAO" }).click();
  await page.getByRole("link", { name: "Get started" }).click();
  await page.getByLabel("Ethereum Sepolia").click();
  await page.getByRole("button", { name: "Next" }).click();
  await page.getByPlaceholder("Type the DAO's name").click();
  await page.getByPlaceholder("Type the DAO's name").fill("E2E Test DAO");
  await page
    .getByPlaceholder("Description of the DAO")
    .fill("DAO generated by automated E2E tests");
  await page.getByRole("button", { name: "Publish DAO" }).click();
  await page.getByRole("button", { name: "Approve transaction" }).click();
  await page.waitForTimeout(3000);
  await metamask.confirmTransaction();
  await page.waitForTimeout(3000);
  await page.getByRole("link", { name: "View DAO" }).click({ timeout: 10000 });
});
