export enum Network {
    ETHEREUM_MAINNET = 'ETHEREUM_MAINNET',
    ETHEREUM_SEPOLIA = 'ETHEREUM_SEPOLIA',
    POLYGON_MAINNET = 'POLYGON_MAINNET',
    ZKSYNC_MAINNET = 'ZKSYNC_MAINNET',
    ZKSYNC_SEPOLIA = 'ZKSYNC_SEPOLIA',
}
