export const Network = {
    ETHEREUM_MAINNET: 'ETHEREUM_MAINNET',
    ETHEREUM_SEPOLIA: 'ETHEREUM_SEPOLIA',
    POLYGON_MAINNET: 'POLYGON_MAINNET',
    BASE_MAINNET: 'BASE_MAINNET',
    ARBITRUM_MAINNET: 'ARBITRUM_MAINNET',
    ZKSYNC_MAINNET: 'ZKSYNC_MAINNET',
    ZKSYNC_SEPOLIA: 'ZKSYNC_SEPOLIA',
    PEAQ_MAINNET: 'PEAQ_MAINNET',
} as const;

export type Network = typeof Network[keyof typeof Network];
