import { testWithSynpress } from '@synthetixio/synpress';
import { metaMaskFixtures } from '@synthetixio/synpress/playwright';
import basicSetup from '../../helpers/wallet.setup';
import { connectWallet } from '../../helpers/connectWallet';

const test = testWithSynpress(metaMaskFixtures(basicSetup));

test('Admin Plugin Test - Create DAO', async ({ page, metamask }) => {
    await connectWallet(page, metamask);
    await page.getByRole('button', { name: 'Create a DAO' }).first().click();
    await page.getByRole('link', { name: 'Get started' }).click();
    await page.getByLabel('Ethereum Sepolia').click();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByLabel('DAO name').fill('E2E Test DAO');
    await page.getByLabel('DescriptionOptionalThis is').fill('DAO generated by automated E2E tests');
    await page.getByRole('button', { name: 'Publish DAO' }).click();
    await page.getByRole('button', { name: 'Approve transaction' }).click();
    await page.waitForTimeout(3000);
    await metamask.confirmTransaction();
    await page.waitForTimeout(3000);
    await page.getByRole('link', { name: 'View DAO' }).click();
});
