name: App E2E Tests - Scheduled

on:
  workflow_dispatch:
  schedule:
    # Runs at 12:00 AM and 12:00 PM
    - cron: "0 0,12 * * *"

jobs:
  build:
    uses: ./.github/workflows/shared-run-e2e-tests.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        environment: [development, production]
    with:
      env: ${{ matrix.environment }}
