name: App E2E Tests - Dispatched

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to run the E2E tests for"
        required: true
        type: choice
        options:
          - "development"
          - "staging"
          - "production"
  repository_dispatch:
    types: ["app_e2e_tests_dispatched"]

env:
  ENVIRONMENT: ${{ github.event.inputs.environment || github.event.client_payload.environment || 'development' }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ env.ENVIRONMENT }}
    steps:
      - run: echo "Running tests on ${{ env.ENVIRONMENT }}"
  test:
    needs: setup
    uses: ./.github/workflows/shared-run-e2e-tests.yml
    secrets: inherit
    with:
      env: ${{ needs.setup.output.env }}
