name: Playwright and Synpress Tests for PRs, Pushes, and Dispatch Events

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - app-next-develop-push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Step 1: Checkout the e2e-tests Repository
      - name: Checkout e2e-tests Repository
        uses: actions/checkout@v4
        with:
          path: ./ # Place the e2e-tests repository in the root directory

      # Step 2: Cache Node.js modules for e2e-tests
      - name: Cache Node.js modules for e2e-tests
        uses: actions/cache@v3
        with:
          path: node_modules
          key: e2e-tests-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            e2e-tests-${{ runner.os }}-
            e2e-tests-
            node_modules

      # Step 3: Install dependencies for e2e-tests with frozen lockfile
      - name: Install dependencies for e2e-tests
        run: yarn install --frozen-lockfile

      # Step 4: Add and initialize the app-next submodule tracking the develop branch (with token authentication)
      - name: Initialize app-next as a submodule (develop branch)
        run: |
          git submodule add https://$GITHUB_ACTOR:${{ secrets.APP_NEXT_ACCESS_TOKEN }}@github.com/aragon/app-next.git ./app-next || true
          cd ./app-next
          git checkout develop
          git pull origin develop
          cd ..
        env:
          GITHUB_ACTOR: ${{ github.actor }}

      # Step 5: Cache Node.js modules for App-Next (after submodule is initialized)
      - name: Cache Node.js modules for App-Next
        uses: actions/cache@v3
        with:
          path: ./app-next/node_modules
          key: app-next-${{ runner.os }}-${{ hashFiles('./app-next/yarn.lock') }}
          restore-keys: |
            app-next-${{ runner.os }}-
            app-next-
            node_modules

      # Step 6: Install dependencies for App-Next with frozen lockfile
      - name: Install dependencies for App-Next
        working-directory: ./app-next
        run: yarn install --frozen-lockfile

      # Step 7: Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('playwright.config.ts') }}
          restore-keys: |
            playwright-${{ runner.os }}-
            playwright-

      # Step 8: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      # Step 9: Build Synpress cache (if needed)
      - name: Build Synpress cache
        run: xvfb-run npx synpress ./tests/
        env:
          METAMASK_SEED_PHRASE: ${{ secrets.METAMASK_SEED_PHRASE }}
          METAMASK_PASSWORD: ${{ secrets.METAMASK_PASSWORD }}

      # Step 10: Start App-Next Development Server with timeout
      - name: Start App-Next Development Server
        working-directory: ./app-next
        run: yarn dev &
        timeout-minutes: 5 # Ensure server doesn't hang indefinitely
        env:
          NEXT_SECRET_IPFS_JWT: ${{ secrets.NEXT_SECRET_IPFS_JWT }}

      # Step 11: Wait for App-Next server to be ready
      - name: Wait for App-Next server to be ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            echo "Waiting for the server to start..."
            sleep 5
          done

      # Step 12: Run E2E tests with Playwright
      - name: Run E2E tests with Playwright
        run: xvfb-run yarn playwright test ./tests/multisig-plugin/02_publishProposal.spec.ts --project=chromium --headless
        env:
          METAMASK_SEED_PHRASE: ${{ secrets.METAMASK_SEED_PHRASE }}
          METAMASK_PASSWORD: ${{ secrets.METAMASK_PASSWORD }}
          NEXT_SECRET_IPFS_JWT: ${{ secrets.NEXT_SECRET_IPFS_JWT }}

      # Step 13: Upload Playwright Report as Artifact
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Step 14: Upload Playwright Artifacts for Debugging (if failure occurs)
      - name: Upload Playwright Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: playwright-artifacts/
