name: Shared Run E2E Tests

on:
  workflow_call:
    inputs:
      env:
        description: "Environment to run the E2E tests for"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: yarn install --immutable
      - name: Prepare secrets
        run: |
          echo "METAMASK_SEED_PHRASE=${{secrets.METAMASK_SEED_PHRASE}}" >> .env
          echo "METAMASK_PASSWORD=${{secrets.METAMASK_PASSWORD}}" >> .env

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(yarn why --json @playwright/test | grep -h 'workspace:.' | jq --raw-output '.children[].locator' | sed -e 's/@playwright\/test@.*://')"
      - name: Restore Playwright cache
        uses: actions/cache@v4.2.3
        id: playwright-cache
        with:
          path: "~/.cache/ms-playwright"
          key: "${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}"
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Setup Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: yarn setup:playwright

      - name: Setup Synpress
        run: xvfb-run yarn setup:synpress

      - name: Run E2E tests
        run: xvfb-run yarn test
        env:
          TEST_ENV: ${{ inputs.env }}
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report-${{ inputs.env }}
          path: playwright-report/
          retention-days: 30
